### PR TITLE
Update Twilio Chat to latest version

### PR DESCRIPTION
**Pull request by jefflinwood**

### CODE REVIEW

**Comment by avaitla** [comment]
Wow, that's awesome! I was just having issues trying to get the master branch working.

**Comment by jefflinwood** [comment]
@avaitla Let me know if you see anything off - I'm happy to jump in and help debug it!

**Comment by avaitla** [comment]
I am noticing that it successfully fetches from the backend but then it just doesn't do much else. See screenshot where the app seems stuck, do you have any troubleshooting recommendation for this situation?

screen shot 2018-10-29 at 4 42 19 pm

**Comment by avaitla** [comment]
I attempted to clear the emulator state (maybe an old build messed something up), using 'xcrun simctl erase all', and then when I rebuild the app into the emulator I get the nasty error (doesn't crash the app):

https://gist.github.com/avaitla/43f256250e4299c2e55da8c1e9c07c6b

However the screen stays stuck loading:

screen shot 2018-10-29 at 4 55 55 pm

When I close the emulator and reload the build it finally loads into this screen:

screen shot 2018-10-29 at 4 57 16 pm

**Comment by avaitla** [comment]
Ultimately I think the code does work, but I have to reload the emulator a few times to get there and I'm not sure how to get it working again.

**Comment by jefflinwood** [comment]
I think I figured out what's going on - there was a UI on background thread exception when running it in the debugger - but only on successful login - after a login, it won't show the login screen - which is why it worked after another try for you.

**Comment by jefflinwood** [comment]
This should be fixed in https://github.com/TwilioDevEd/twiliochat-swift/pull/29

**Comment by avaitla** [comment]
Thanks

**Pull request merged**
